[package]
name = "rust_dxlib"
version = "0.1.0"
authors = ["パン粉 ライ麦 <relipmoc101@gmail.com>"]

repository = "https://github.com/elipmoc/rust_dxlib"
build="build.rs"

readme = "README.md"

license = "MIT"


[lib]
name="rust_dxlib"
path="src/lib.rs"